In [3]:
#Read titanic dataset and perform following operations and observe output
import pandas as pd
import numpy as np
read_df = pd.read_excel('/content/Titanic-Dataset (2).xlsx')
read_df

#2. Find max and min fairprice of each Pclass (1 and 2 and 3)
#3. Handle missing values in age and cabin columns
#4. Find average fair price of lower class people (Pclass = 3) who survived
#5. Learn dna implement how to find duplicate columns and rows and how to remove them

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#2. Find max and min fairprice of each Pclass (1 and 2 and 3)
Pclass_stats = read_df.groupby('Pclass')['Fare'].agg(['max','min'])
Pclass_stats

             max  min
Pclass
1       512.3292  0.0
2        73.5000  0.0
3        69.5500  0.0

In [ ]:
#. 3Handle missing values in age and cabin columns
df_no_missing = read_df.copy()
df_no_missing['Age'] = df_no_missing['Age'].fillna(df_no_missing['Age'].median())
df_no_missing['Cabin'] = df_no_missing['Cabin'].fillna('Unknown')
df_no_missing

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Unknown,Q

In [6]:
#4. Find average fair price of lower class people (Pclass = 3) who survived

average_fare = read_df[(read_df['Pclass'] == 3) & (read_df['Survived'] == 1)]['Fare'].mean()
print(f"The average fare for lower class survivors is: {average_fare}")

The average fare for lower class survivors is: 13.69488739495798

In [ ]:
#5. Learn dna implement how to find duplicate columns and rows and how to remove them
duplicate_cols = read_df.columns[read_df.columns.duplicated()]
print("Dupliacte columns:", duplicate_cols)
read_df = read_df.loc[:, ~read_df.columns.duplicated()]
duplicate_rows = read_df[read_df.duplicated()]
print("\nDuplicate rows:\n", duplicate_rows)
read_df = read_df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", read_df)

Dupliacte columns: Index([], dtype='object')

Duplicate rows:
 Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, gender, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

DataFrame after removing duplicates:
      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500  Unknown        S
1        0          PC 17599  71.2833      C85        C
2        0  STON/O2. 3101282   7.9250  Unknown        S
3        0            113803  53.1000     C123        S
4        0            373450   8.0500  Unknown        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000  Unknown        S
887      0            112053  30.0000      B42        S
888      2        W./C. 6607  23.4500  Unknown        S
889      0            111369  30.0000     C148        C
890      0            370376   7.7500  Unknown        Q

[891 rows x 12 columns]